use  master 
go
if DB_ID ('DDS_ACC1') IS NOT NULL
    DROP DATABASE DDS_ACC1
GO
CREATE DATABASE DDS_ACC1
GO
USE DDS_ACC1
GO

--DIM_DATE
CREATE TABLE [dbo].[DIM_DATE](
	[DATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE_FULL_NUMBER] [int] NULL,
	[DATE_FULL_STRING] DATETIME NULL,
	[DATE_HOLIDAY] [bit] NULL,
	[DATE_NAME] [varchar](50) NULL,
	DAY_KEY INT NULL,
	[WEEK_KEY] [int] NULL, --STT WEEK
	[MONTH_KEY] [int] NULL, --STT MONTH
	MONTH_NAME VARCHAR(10),
	[QUARTER_KEY] [int] NULL,--STT QUARTER
	[YEAR_KEY] [int] NULL,--STT YEAR
	DATE_NUMBER_OF_WEEK INT,
	DATE_NUMBER_OF_MONTH INT,
	DATE_NUMBER_OF_QUARTER INT,
	DATE_NUMBER_OF_YEAR INT,

 CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_ID)
 )
 --DIM ACCIDENT
 CREATE TABLE [dbo].[DIM_ACCIDENTS](
	ACCIDENT_ID int  NOT NULL,
    ACCIDENT_INDEX CHAR(13),
    LOCAL_AUTHORITY_DISTRICT_KEY INT,
	LOCAL_AUTHORITY_DISTRICT CHAR(50),
    LOCAL_AUTHORITY_HIGHWAY INT,
    DATE_ACC DATETIME,
	ACCIDENT_SEVERITY_KEY INT,
	ACCIDENT_SEVERITY CHAR(10),
	TIME_PERIOD_ID INT,
	TIME_PERIOD CHAR(30),
	URBAN_OR_RURAL CHAR(1),
	ROAD_TYPE_KEY INT,
	LOCATION_EASTING CHAR(6),
	LOCATION_NORTHING CHAR(6),
	LONGITUDE CHAR(10),
	LATITUDE CHAR(10),
	LSOA CHAR(50),
	CITY CHAR(50),
	COUNTY CHAR(30),
	NUMBER_OF_CASUALTIES INT,
	SOURCE_ID INT,
	BUILD_UP_ROAD INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME,
	CONSTRAINT PK_DIM_ACCIDENT PRIMARY KEY (ACCIDENT_ID)
)
--DIM_AGE_BAND
CREATE TABLE DIM_AGE_BAND
(
    AGE_BAND_ID INT  NOT NULL,
	AGE_BAND_KEY INT,
	AGE_BAND CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_AGE_BAND
    PRIMARY KEY (AGE_BAND_ID)
)
--DIM_AGE_GROUP
CREATE TABLE DIM_AGE_GROUP
(
    AGE_GROUP_ID INT  NOT NULL,
	AGE_GROUP_KEY INT,
	AGE_GROUP CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_AGE_GROUP
    PRIMARY KEY (AGE_GROUP_ID)
)
--DIM_GENDER
CREATE TABLE DIM_GENDER
(
    GENDER_ID INT  NOT NULL,
	GENDER_KEY INT,
	GENDER VARCHAR(10),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_GENDER
    PRIMARY KEY (GENDER_ID)
)
--DIM_CAS_SEVE
CREATE TABLE DIM_CASUAL_SEVERITY
(
    CASUAL_SEVERITY_ID INT  NOT NULL,
	CASUAL_SEVERITY_KEY INT,
	CASUAL_SEVERITY CHAR(10),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_CASUAL_SEVERITY
    PRIMARY KEY (CASUAL_SEVERITY_ID)
)
--DIM_CAS_TYPE
CREATE TABLE DIM_CASUAL_TYPE
(
    CASUAL_TYPE_ID INT  NOT NULL,
	CASUAL_TYPE_KEY INT,
	CASUAL_TYPE CHAR(300),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_CASUAL_TYPE
    PRIMARY KEY (CASUAL_TYPE_ID)
)
--FACT_CASUALTY
CREATE TABLE FACT_CASUALTY
(
	FACT_CASUALTY_ID INT  NOT NULL,
	ACCIDENT_INDEX CHAR(13),
	VEHICLE_REFERENCE INT,
	CASUALTY_REFERENCE INT,
	ACCIDENT_ID INT,
	DATE_ID INT,
	CASUALTY_SEVERITY_ID INT,
	GENDER_ID INT,
	CASUALTY_TYPE_ID INT,
	AGE_BAND_ID INT,
	AGE_GROUP_ID INT,
	LOCAL_AUTHORITY_DISTRICT_ID INT,
	NUMBER_OF_CASUALTY INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_FACT_CASUAL
    PRIMARY KEY (ACCIDENT_INDEX, VEHICLE_REFERENCE, CASUALTY_REFERENCE)
)
--DIM_JOUNEY_PURPOSE
CREATE TABLE DIM_JOUNEY_PURPOSE
(
    JOUNEY_PURPOSE_ID INT  NOT NULL,
	JOUNEY_PURPOSE_KEY INT,
	JOUNEY_PURPOSE CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME
	CONSTRAINT PK_JOUNEY_PURPOSE
    PRIMARY KEY (JOUNEY_PURPOSE_ID)
)
--DIM_VEHICLE_TYPE

CREATE TABLE DIM_VEHICLE_TYPE
(
    VEHICLES_TYPE_ID INT  NOT NULL,
	VEHICLES_TYPE_KEY INT,
	VEHICLES_TYPE CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_VEHICLES_TYPE
    PRIMARY KEY (VEHICLES_TYPE_ID)
)
--FACT_VEHICLE
CREATE TABLE FACT_VEHICLE
(
	FACT_VEHICLE_ID INT  NOT NULL,
	ACCIDENT_INDEX CHAR(13),
	VEHICLE_REFERENCE INT,
	ACCIDENT_ID INT,
	DATE_ID INT,
	JOUNEY_PURPOSE_ID INT,
	VEHICLE_TYPE_ID INT,
	BUILD_UP_ROAD_ID INT,
	ACCIDENTS_SEVERITY INT,
	NUMBER_OF_VEHICLE INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_FACT_VEHICLE
    PRIMARY KEY (ACCIDENT_INDEX, VEHICLE_REFERENCE)
)
--DIM_TIME_PERIOD
CREATE TABLE DIM_TIME_PERIOD
(
    TIME_PERIOD_ID INT  NOT NULL,
	TIME_PERIOD_KEY INT,
	TIME_PERIOD CHAR(25),
	PERIOD_NAME CHAR(25),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_TIME_PERIOD
    PRIMARY KEY (TIME_PERIOD_ID)
)
--DIM_URBAN_RURAL
CREATE TABLE DIM_URBAN_RURAL
(
    URBAN_RURAL_ID INT  NOT NULL,
	URBAN_RURAL_KEY INT,
	URBAN_RURAL_NAME CHAR(20),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_URBAN_RURAL
    PRIMARY KEY (URBAN_RURAL_ID)
)
--DIM_ACCIDENT_SEVE
CREATE TABLE DIM_ACCIDENT_SEVERITY
(
    ACCIDENT_SEVERITY_ID INT  NOT NULL,
	ACCIDENT_SEVERITY_KEY INT,
	ACCIDENT_SEVERITY CHAR(10),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_ACCIDENT_SEVERITY
    PRIMARY KEY (ACCIDENT_SEVERITY_ID)
)
--DIM_ROAD_TYPE
CREATE TABLE DIM_ROAD_TYPE
(
    ROAD_TYPE_ID INT  NOT NULL,
	ROAD_TYPE_KEY INT,
	ROAD_TYPE CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_ROAD_TYPE
    PRIMARY KEY (ROAD_TYPE_ID)
)
--FACT_ACCIDENT
CREATE TABLE FACT_ACCIDENT
(
	FACT_ACCIDENT_ID INT NOT NULL,
	ACCIDENT_INDEX CHAR(13),
	TIME_PERIOD_ID INT,
	ACCIDENT_SEVERITY_ID INT,
	DATE_ID INT,
	URBAN_RURAL_ID INT,
	ROAD_TYPE_ID INT,
	NUMBER_OF_ACCIDENT INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_FACT_ACCIDENT
    PRIMARY KEY (ACCIDENT_INDEX)
)
--SET FK 
--FACT_CASUALTY
ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_ACCIDENT
FOREIGN KEY(ACCIDENT_ID) 
REFERENCES dbo.DIM_ACCIDENTS(ACCIDENT_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_DATE
FOREIGN KEY(DATE_ID) 
REFERENCES dbo.DIM_DATE(DATE_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_CAS_SEVE
FOREIGN KEY(CASUALTY_SEVERITY_ID) 
REFERENCES dbo.DIM_CASUAL_SEVERITY(CASUAL_SEVERITY_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_GENDER
FOREIGN KEY(GENDER_ID) 
REFERENCES dbo.DIM_GENDER(GENDER_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_AGE_BAND
FOREIGN KEY(AGE_BAND_ID) 
REFERENCES dbo.DIM_AGE_BAND(AGE_BAND_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_CAS_TYPE
FOREIGN KEY(CASUALTY_TYPE_ID) 
REFERENCES dbo.DIM_CASUAL_TYPE(CASUAL_TYPE_ID)

ALTER TABLE dbo.FACT_CASUALTY
ADD CONSTRAINT FK_FC_DIM_AGE_GROUP
FOREIGN KEY(AGE_GROUP_ID) 
REFERENCES dbo.DIM_AGE_GROUP(AGE_GROUP_ID)

--FK FACT VEHICLE
ALTER TABLE dbo.FACT_VEHICLE
ADD CONSTRAINT FK_FV_DIM_ACCIDENTS
FOREIGN KEY(ACCIDENT_ID) 
REFERENCES dbo.DIM_ACCIDENTS(ACCIDENT_ID)

ALTER TABLE dbo.FACT_VEHICLE
ADD CONSTRAINT FK_FV_DIM_DATE
FOREIGN KEY(DATE_ID) 
REFERENCES dbo.DIM_DATE(DATE_ID)

ALTER TABLE dbo.FACT_VEHICLE
ADD CONSTRAINT FK_FV_DIM_VEHICLE_TYPE
FOREIGN KEY(VEHICLE_TYPE_ID) 
REFERENCES dbo.DIM_VEHICLE_TYPE(VEHICLES_TYPE_ID)

ALTER TABLE dbo.FACT_VEHICLE
ADD CONSTRAINT FK_FV_DIM_JOUNEY_PURPOSE
FOREIGN KEY(JOUNEY_PURPOSE_ID) 
REFERENCES dbo.DIM_JOUNEY_PURPOSE(JOUNEY_PURPOSE_ID)

ALTER TABLE dbo.FACT_VEHICLE
ADD CONSTRAINT FK_FV_DIM_ACCIDENT_SEVERITY
FOREIGN KEY (ACCIDENTS_SEVERITY) 
REFERENCES dbo.DIM_ACCIDENT_SEVERITY(ACCIDENT_SEVERITY_ID)

--FK FACT ACCIDENT
ALTER TABLE dbo.FACT_ACCIDENT
ADD CONSTRAINT FK_FA_DIM_TIME_PERIOD
FOREIGN KEY(TIME_PERIOD_ID) 
REFERENCES dbo.DIM_TIME_PERIOD(TIME_PERIOD_ID)

ALTER TABLE dbo.FACT_ACCIDENT
ADD CONSTRAINT FK_FA_DIM_ACCIDENT_SEVERITY
FOREIGN KEY(ACCIDENT_SEVERITY_ID) 
REFERENCES dbo.DIM_ACCIDENT_SEVERITY(ACCIDENT_SEVERITY_ID)

ALTER TABLE dbo.FACT_ACCIDENT
ADD CONSTRAINT FK_FA_DIM_DATE
FOREIGN KEY(DATE_ID) 
REFERENCES dbo.DIM_DATE(DATE_ID)

ALTER TABLE dbo.FACT_ACCIDENT
ADD CONSTRAINT FK_FA_DIM_ROAD_TYPE
FOREIGN KEY(ROAD_TYPE_ID) 
REFERENCES dbo.DIM_ROAD_TYPE(ROAD_TYPE_ID)

ALTER TABLE dbo.FACT_ACCIDENT
ADD CONSTRAINT FK_FA_DIM_URBAN_RURAL
FOREIGN KEY(URBAN_RURAL_ID) 
REFERENCES dbo.DIM_URBAN_RURAL(URBAN_RURAL_ID)



CREATE TABLE DIM_LOCAL_AUTHORITY_DISTRICT
(
	LOCAL_AUTHORITY_DISTRICT_ID INT  NOT NULL,
	LOCAL_AUTHORITY_DISTRICT_KEY INT,
	LOCAL_AUTHORITY_DISTRICT CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_LOCAL_DISTRICT
    PRIMARY KEY (LOCAL_AUTHORITY_DISTRICT_ID)
)

ALTER TABLE FACT_CASUALTY
ADD CONSTRAINT FK_FC_LOCAL_DISTRICT
FOREIGN KEY (LOCAL_AUTHORITY_DISTRICT_ID)
REFERENCES DBO.DIM_LOCAL_AUTHORITY_DISTRICT(LOCAL_AUTHORITY_DISTRICT_ID)


CREATE TABLE DIM_BUILD_UP_ROAD
(
	BUILD_UP_ROAD_ID INT NOT NULL,
	BUILD_UP_ROAD CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_BUILD_UP_ROAD
    PRIMARY KEY (BUILD_UP_ROAD_ID)
)

ALTER TABLE FACT_VEHICLE
ADD CONSTRAINT FK_FC_VEHICLE_BUR
FOREIGN KEY (BUILD_UP_ROAD_ID)
REFERENCES DIM_BUILD_UP_ROAD(BUILD_UP_ROAD_ID)