USE META_UK

SELECT * FROM TABLE_INFO

--TRUNCATE TABLE NDS_TABLE_INFO
--drop table DDS_TABLE_INFO

CREATE TABLE DDS_TABLE_INFO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TABLE_NAME VARCHAR(30),
	LSET DATETIME,
	CET DATETIME,
	DESCRIBE VARCHAR(50),
	NUMBER_OF_RECORD INT
)



INSERT INTO DDS_TABLE_INFO VALUES ('DIM_LOCAL_AUTHORITY_DISTRICT','2021-01-01',NULL,NULL,NULL)
INSERT INTO DDS_TABLE_INFO VALUES ('DIM_BUILD_UP_ROAD','2021-01-01',NULL,NULL,NULL)





