use  master 
go
if DB_ID ('NDS_ACC') IS NOT NULL
    DROP DATABASE NDS_ACC
GO
CREATE DATABASE NDS_ACC
GO
USE NDS_ACC
GO

CREATE TABLE ACCIDENTS
(
	ACCIDENT_ID int IDENTITY(1,1) NOT NULL,
    ACCIDENT_INDEX CHAR(13) unique,
    LOCAL_AUTHORITY_DISTRICT_ID INT,
    LOCAL_AUTHORITY_HIGHWAY INT,
    DATE_ACC DATETIME,
	ACCIDENT_SEVERITY_KEY INT,
	TIME_PERIOD_ID INT,
	URBAN_OR_RURAL INT,
	ROAD_TYPE_KEY INT,
	BUILD_UP_ROAD INT,
	LOCATION_EASTING CHAR(6),
	LOCATION_NORTHING CHAR(6),
	LONGITUDE CHAR(10),
	LATITUDE CHAR(10),
	LSOA CHAR(50),
	NUMBER_OF_CASUALTIES INT,
	SOURCE_ID INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

    CONSTRAINT PK_ACCIDENTS
    PRIMARY KEY (ACCIDENT_ID)
)

CREATE TABLE URBAN_RURAL
(
	URBAN_RURAL_ID INT IDENTITY(1,1) NOT NULL,
	URBAN_RURAL_KEY INT,
	URBAN_RURAL CHAR(15),
	CREATED_DATE DATE,
	UPDATE_DATE DATE

	CONSTRAINT PK_URBAN_RURAL
	PRIMARY KEY (URBAN_RURAL_ID)
)

CREATE TABLE VEHICLES
(
	VEHICLE_ID int IDENTITY(1,1) NOT NULL,
    ACCIDENT_INDEX CHAR(13),
	VEHICLE_REFERENCE INT,
	ACCIDENT_ID INT,
    VEHICLE_TYPE_KEY INT,
	JOUNEY_PURPOSE_KEY INT,
	SOURCE_ID INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

    CONSTRAINT PK_VEHICLES
    PRIMARY KEY (VEHICLE_ID)
)
CREATE TABLE CASUALTIES
(
	CASUALTY_ID int IDENTITY(1,1) NOT NULL,
    ACCIDENT_INDEX CHAR(13),
	VEHICLE_REFERENCE INT,
	CASUALTY_REFERENCE INT,
	ACCIDENT_ID INT,
	VEHICLE_ID INT,
	CASUAL_SEVERITY int,
	CASUALTY_GENDER_KEY INT,
	CASUAL_TYPE_KEY INT,
	AGE_BAND_KEY INT,
	AGE_GROUP_KEY INT,
	PEDESTRIAN_LOCATION INT,
	PEDESTRIAN_MOVEMENT INT,
	PEDESTRIAN_ROAD_MAINTENANCE_WORKER INT,
	CASUALTY_CLASS INT,
	SOURCE_ID INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

    CONSTRAINT PK_CASUALTIES
    PRIMARY KEY (CASUALTY_ID)
)

CREATE TABLE CASUALTY_GENDER
(
	GENDER_ID INT IDENTITY(1,1) NOT NULL,
	GENDER_KEY INT,
	GENDER CHAR(10),
	CREATED_DATE DATE,
	UPDATE_DATE DATE

	CONSTRAINT PK_GENDER
	PRIMARY KEY (GENDER_ID)
)

CREATE TABLE POSTCODE
(
	POSTCODE_ID int IDENTITY(1,1) NOT NULL,
    POSTCODE CHAR(10) unique,
    EASTING CHAR(10),
	NORTHING CHAR(10),
	LONGITUDE CHAR(10),
	LATITUDE CHAR(10),
	CITY CHAR(50),
	COUNTY CHAR (30),
	COUNTRY_KEY CHAR(3),
	REGION CHAR(9),
	ISO_3166_2 CHAR(50),
	SOURCE_ID INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

    CONSTRAINT PK_POSTCODE
    PRIMARY KEY (POSTCODE_ID)
)
CREATE TABLE LSOA_INFO
(
	LSOA_INFO_ID int IDENTITY(1,1) NOT NULL,
    POSTCODE_7 CHAR(10),
	POSTCODE_8 CHAR(10),
	POSTCODE_S CHAR(10),
	LSOA CHAR(50),
	SOURCE_ID INT,
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME
    
	CONSTRAINT PK_LSOA_INFO
    PRIMARY KEY (LSOA_INFO_ID)
)
--CASUAL
CREATE TABLE CASUAL_TYPE
(
    CASUAL_TYPE_ID INT IDENTITY(1,1) NOT NULL,
	CASUAL_TYPE_KEY INT,
	CASUAL_TYPE CHAR(300),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_CASUAL_TYPE
    PRIMARY KEY (CASUAL_TYPE_ID)
    
)
CREATE TABLE AGE_BAND
(
    AGE_BAND_ID INT IDENTITY(1,1) NOT NULL,
	AGE_BAND_KEY INT,
	AGE_BAND CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_AGE_BAND
    PRIMARY KEY (AGE_BAND_ID)
    
)

CREATE TABLE AGE_GROUP
(
    AGE_GROUP_ID INT IDENTITY(1,1) NOT NULL,
	AGE_GROUP_KEY INT,
	AGE_GROUP CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_AGE_GROUP
    PRIMARY KEY (AGE_GROUP_ID)
    
)
CREATE TABLE CASUAL_SEVERITY
(
    CASUAL_SEVERITY_ID INT IDENTITY(1,1) NOT NULL,
	CASUAL_SEVERITY_KEY INT,
	CASUAL_SEVERITY CHAR(10),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_CASUAL_SEVERITY
    PRIMARY KEY (CASUAL_SEVERITY_ID)
)
--VEHICLES
CREATE TABLE VEHICLES_TYPE
(
    VEHICLES_TYPE_ID INT IDENTITY(1,1) NOT NULL,
	VEHICLES_TYPE_KEY INT,
	VEHICLES_TYPE CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_VEHICLES_TYPE
    PRIMARY KEY (VEHICLES_TYPE_ID)
)
CREATE TABLE JOUNEY_PURPOSE
(
    JOUNEY_PURPOSE_ID INT IDENTITY(1,1) NOT NULL,
	JOUNEY_PURPOSE_KEY INT,
	JOUNEY_PURPOSE CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME
	CONSTRAINT PK_JOUNEY_PURPOSE
    PRIMARY KEY (JOUNEY_PURPOSE_ID)
)
--ACCIDENTS
CREATE TABLE ROAD_TYPE
(
    ROAD_TYPE_ID INT IDENTITY(1,1) NOT NULL,
	ROAD_TYPE_KEY INT,
	ROAD_TYPE CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_ROAD_TYPE
    PRIMARY KEY (ROAD_TYPE_ID)
)
CREATE TABLE ACCIDENTS_SEVERITY
(
    ACCIDENTS_SEVERITY_ID INT IDENTITY(1,1) NOT NULL,
	ACCIDENTS_SEVERITY_KEY INT,
	ACCIDENTS_SEVERITY CHAR(10),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_ACCIDENTS_SEVERITY
    PRIMARY KEY (ACCIDENTS_SEVERITY_ID)
)
--POSTCODE
CREATE TABLE COUNTRY
(
    COUNTRY_ID INT IDENTITY(1,1) NOT NULL,
	COUNTRY_KEY CHAR(3),
	COUNTRY CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_COUNTRY
    PRIMARY KEY (COUNTRY_ID)
)
--SOUCE TABLE
CREATE TABLE SOURCE
(
    SOURCE_ID INT IDENTITY(1,1) NOT NULL,
	SOURCE_KEY INT,
	SOURCE CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_SOURCE
    PRIMARY KEY (SOURCE_ID)
)

--INSERT
--URBAN RURAL
INSERT INTO URBAN_RURAL VALUES (1,'Urban',null,null)
INSERT INTO URBAN_RURAL VALUES (2,'Rural',null,null)
INSERT INTO URBAN_RURAL VALUES (3,'Unallocated',null,null)

ALTER TABLE dbo.ACCIDENTS 
ADD CONSTRAINT FK_ACCIDENTS_URBAN_RURAL
FOREIGN KEY(URBAN_OR_RURAL) 
REFERENCES dbo.URBAN_RURAL(URBAN_RURAL_ID)


--CTYPE
INSERT INTO CASUAL_TYPE VALUES (0, 'Pedestrian',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (1, 'Cyclist',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (2, 'Motorcycle 50cc and under rider or passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (3, 'Motorcycle 125cc and under rider or passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (4, 'Motorcycle over 125cc and up to 500cc rider or  passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (5, 'Motorcycle over 500cc rider or passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (8, 'Taxi/Private hire car occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (9, 'Car occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (10, 'Minibus (8 - 16 passenger seats) occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (11, 'Bus or coach occupant (17 or more pass seats)',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (16, 'Horse rider',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (17, 'Agricultural vehicle occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (18, 'Tram occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (19, 'Van / Goods vehicle (3.5 tonnes mgw or under) occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (20, 'Goods vehicle (over 3.5t. and under 7.5t.) occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (21, 'Goods vehicle (7.5 tonnes mgw and over) occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (22, 'Mobility scooter rider',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (23, 'Electric motorcycle rider or passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (90, 'Other vehicle occupant',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (97, 'Motorcycle - unknown cc rider or passenger',NULL,NULL);
INSERT INTO CASUAL_TYPE VALUES (98, 'Goods vehicle (unknown weight) occupant',NULL,NULL);
--AGE_BAND
INSERT INTO AGE_BAND VALUES (1, '0 - 5',NULL,NULL);
INSERT INTO AGE_BAND VALUES (2, '6 - 10',NULL,NULL);
INSERT INTO AGE_BAND VALUES (3, '11 - 15',NULL,NULL);
INSERT INTO AGE_BAND VALUES (4, '16 - 20',NULL,NULL);
INSERT INTO AGE_BAND VALUES (5, '21 - 25',NULL,NULL);
INSERT INTO AGE_BAND VALUES (6, '26 - 35',NULL,NULL);
INSERT INTO AGE_BAND VALUES (7, '36 - 45',NULL,NULL);
INSERT INTO AGE_BAND VALUES (8, '46 - 55',NULL,NULL);
INSERT INTO AGE_BAND VALUES (9, '56 - 65',NULL,NULL);
INSERT INTO AGE_BAND VALUES (10, '66 - 75',NULL,NULL);
INSERT INTO AGE_BAND VALUES (11, 'Over 75',NULL,NULL);
INSERT INTO AGE_BAND VALUES (-1, 'Data missing or out of range',NULL,NULL);
--AGE_GROUP
INSERT INTO AGE_GROUP VALUES (1, 'CHILDREN',NULL,NULL);
INSERT INTO AGE_GROUP VALUES (2, 'TEENAGER',NULL,NULL);
INSERT INTO AGE_GROUP VALUES (3, 'ALDULT',NULL,NULL);
INSERT INTO AGE_GROUP VALUES (4, 'ELDER',NULL,NULL);
INSERT INTO AGE_GROUP VALUES (5, 'ERROR',NULL,NULL);
--CASUAL_SEVERITY
INSERT INTO CASUAL_SEVERITY VALUES (1, 'Fatal',NULL,NULL);
INSERT INTO CASUAL_SEVERITY VALUES (2, 'Serious',NULL,NULL);
INSERT INTO CASUAL_SEVERITY VALUES (3, 'Slight',NULL,NULL);
--VEHICLES_TYPE
INSERT INTO VEHICLES_TYPE VALUES (1, 'Pedal cycle',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (2, 'Motorcycle 50cc and under',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (3, 'Motorcycle 125cc and under',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (4, 'Motorcycle over 125cc and up to 500cc',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (5, 'Motorcycle over 500cc',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (8, 'Taxi/Private hire car',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (9, 'Car',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (10, 'Minibus (8 - 16 passenger seats)',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (11, 'Bus or coach (17 or more pass seats)',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (16, 'Ridden horse',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (17, 'Agricultural vehicle',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (18, 'Tram',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (19, 'Van / Goods 3.5 tonnes mgw or under',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (20, 'Goods over 3.5t. and under 7.5t',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (21, 'Goods 7.5 tonnes mgw and over',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (22, 'Mobility scooter',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (23, 'Electric motorcycle',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (90, 'Other vehicle',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (97, 'Motorcycle - unknown cc',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (98, 'Goods vehicle - unknown weight',NULL,NULL);
INSERT INTO VEHICLES_TYPE VALUES (-1, 'Data missing or out of range',NULL,NULL);
--JOUNEY_PURPOSE
INSERT INTO JOUNEY_PURPOSE VALUES (1, 'Journey as part of work',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (2, 'Commuting to/from work',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (3, 'Taking pupil to/from school',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (4, 'Pupil riding to/from school',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (5, 'Other',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (6, 'Not known',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (15, 'Other/Not known (2005-10)',NULL,NULL);
INSERT INTO JOUNEY_PURPOSE VALUES (-1, 'Data missing or out of range',NULL,NULL);
--ROAD_TYPE
INSERT INTO ROAD_TYPE VALUES (1, 'Roundabout',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (2, 'One way street',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (3, 'Dual carriageway',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (6, 'Single carriageway',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (7, 'Slip road',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (9, 'Unknown',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (12, 'One way street/Slip road',NULL,NULL);
INSERT INTO ROAD_TYPE VALUES (-1, 'Data missing or out of range',NULL,NULL);
--ACCIDENTS_SEVERITY
INSERT INTO ACCIDENTS_SEVERITY VALUES (1, 'Fatal',NULL,NULL);
INSERT INTO ACCIDENTS_SEVERITY VALUES (2, 'Serious',NULL,NULL);
INSERT INTO ACCIDENTS_SEVERITY VALUES (3, 'Slight',NULL,NULL);
--COUNTRY
INSERT INTO COUNTRY VALUES ('ENG', 'ENGLAND',NULL,NULL);
INSERT INTO COUNTRY VALUES ('GGY', 'GUEMSEY',NULL,NULL);
INSERT INTO COUNTRY VALUES ('IMN', 'ISLE OF MAN',NULL,NULL);
INSERT INTO COUNTRY VALUES ('JEY', 'JERSEY',NULL,NULL);
INSERT INTO COUNTRY VALUES ('NIR', 'NORTHERN IRELAND',NULL,NULL);
INSERT INTO COUNTRY VALUES ('SCT', 'SCOTLAND',NULL,NULL);
INSERT INTO COUNTRY VALUES ('WLS', 'WALES',NULL,NULL);
--SOURCE
INSERT INTO SOURCE VALUES (1,'FLAT_FILE',NULL,NULL)

-- KHOA NGOAI
--ALTER TABLE LSOA_INFO
--DROP CONSTRAINT PK_LSOA_INFO
-- TAO KHOA NGOAI

--ALTER TABLE dbo.ACCIDENTS 
--ADD CONSTRAINT FK_ACCIDENTS_LSOA 
--FOREIGN KEY(LSOA) 
--REFERENCES dbo.LSOA_INFO(LSOA)

ALTER TABLE dbo.CASUALTIES 
ADD CONSTRAINT FK_CASUALTIES_ACCIDENTS
FOREIGN KEY(ACCIDENT_ID) 
REFERENCES dbo.ACCIDENTS(ACCIDENT_ID)

ALTER TABLE dbo.VEHICLES 
ADD CONSTRAINT FK_VEHICLES_ACCIDENTS
FOREIGN KEY(ACCIDENT_ID) 
REFERENCES dbo.ACCIDENTS(ACCIDENT_ID)

--ALTER TABLE dbo.LSOA_INFO 
--ADD CONSTRAINT FK_LSOA_POSTCODE
--FOREIGN KEY(POSTCODE_7) 
--REFERENCES dbo.POSTCODE(POSTCODE)

ALTER TABLE DBO.CASUALTIES
ADD CONSTRAINT FK_CASUALTIES_VEHICLE
FOREIGN KEY(VEHICLE_ID) 
REFERENCES dbo.VEHICLES(VEHICLE_ID)

--FK CASUALTIES
ALTER TABLE dbo.CASUALTIES
ADD CONSTRAINT FK_CASUAL_CTYPE
FOREIGN KEY(CASUAL_TYPE_KEY) 
REFERENCES dbo.CASUAL_TYPE(CASUAL_TYPE_ID)

ALTER TABLE dbo.CASUALTIES
ADD CONSTRAINT FK_CASUAL_AGE_BAND
FOREIGN KEY(AGE_BAND_KEY) 
REFERENCES dbo.AGE_BAND(AGE_BAND_ID)

ALTER TABLE dbo.CASUALTIES
ADD CONSTRAINT FK_CASUAL_AGE_GROUP
FOREIGN KEY(AGE_GROUP_KEY) 
REFERENCES dbo.AGE_GROUP(AGE_GROUP_ID)

ALTER TABLE dbo.CASUALTIES
ADD CONSTRAINT FK_CASUAL_CSEVE
FOREIGN KEY(CASUAL_SEVERITY) 
REFERENCES dbo.CASUAL_SEVERITY(CASUAL_SEVERITY_ID)

--FK VEHICLES
ALTER TABLE dbo.VEHICLES
ADD CONSTRAINT FK_VEHICLES_VTYPE
FOREIGN KEY(VEHICLE_TYPE_KEY) 
REFERENCES dbo.VEHICLES_TYPE(VEHICLES_TYPE_ID)

ALTER TABLE dbo.VEHICLES
ADD CONSTRAINT FK_VEHICLES_JPURPOSE
FOREIGN KEY(JOUNEY_PURPOSE_KEY) 
REFERENCES dbo.JOUNEY_PURPOSE(JOUNEY_PURPOSE_ID)

--ACCIDENTS

ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_RTYPE
FOREIGN KEY(ROAD_TYPE_KEY) 
REFERENCES dbo.ROAD_TYPE(ROAD_TYPE_ID)

ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_ASEVE
FOREIGN KEY(ACCIDENT_SEVERITY_KEY) 
REFERENCES dbo.ACCIDENTS_SEVERITY(ACCIDENTS_SEVERITY_ID)

--POSTCODE
/*ALTER TABLE dbo.POSTCODE
ADD CONSTRAINT FK_POSTCODE_COUNTRY
FOREIGN KEY(COUNTRY_KEY) 
REFERENCES dbo.COUNTRY(COUNTRY_ID)*/

--SOURCE
ALTER TABLE dbo.CASUALTIES
ADD CONSTRAINT FK_CASUALTIES_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
/*
ALTER TABLE dbo.CASUAL_TYPE
ADD CONSTRAINT FK_CTYPE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

ALTER TABLE dbo.AGE_BAND
ADD CONSTRAINT FK_AGE_BAND_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

ALTER TABLE dbo.AGE_GROUP
ADD CONSTRAINT FK_AGE_GROUP_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

ALTER TABLE dbo.CASUAL_SEVERITY
ADD CONSTRAINT FK_CSEVE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
*/
ALTER TABLE dbo.VEHICLES
ADD CONSTRAINT FK_VEHICLES_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
/*
ALTER TABLE dbo.VEHICLES_TYPE
ADD CONSTRAINT FK_VTYPE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

ALTER TABLE dbo.JOUNEY_PURPOSE
ADD CONSTRAINT FK_JPOSE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
*/
ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
/*
ALTER TABLE dbo.ROAD_TYPE
ADD CONSTRAINT FK_RTYPE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

ALTER TABLE dbo.ACCIDENTS_SEVERITY
ADD CONSTRAINT FK_ASEVE_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
*/
ALTER TABLE dbo.POSTCODE
ADD CONSTRAINT FK_POSTCODES_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
/*
ALTER TABLE dbo.COUNTRY
ADD CONSTRAINT FK_COUNTRY_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)
*/
ALTER TABLE dbo.LSOA_INFO
ADD CONSTRAINT FK_LSOA_SOURCE
FOREIGN KEY(SOURCE_ID) 
REFERENCES dbo.SOURCE(SOURCE_ID)

INSERT INTO CASUALTY_GENDER VALUES (1,'Male',null,null)
INSERT INTO CASUALTY_GENDER VALUES (2,'Female',null,null)
INSERT INTO CASUALTY_GENDER VALUES (3,'Not known',null,null)
INSERT INTO CASUALTY_GENDER VALUES (-1,'Error',null,null)

ALTER TABLE DBO.CASUALTIES
ADD CONSTRAINT FK_CASUALTIES_GENDER
FOREIGN KEY (CASUALTY_GENDER_KEY)
REFERENCES DBO.CASUALTY_GENDER(GENDER_ID)



CREATE TABLE LOCAL_AUTHORITY_HIGHWAY
(
    LAH_ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    LOCAL_AUTHORITY_HIGHWAY CHAR(50),
    LOCAL_AUTHORITY_HIGHWAY_KEY CHAR(12),
    SOURCE_ID INT,
    CREATED_DATE DATETIME,
    UPDATE_DATE DATETIME
)

INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000033','Aberdeen City');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000034','Aberdeenshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000041','Angus');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000035','Argyll & Bute');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000002','Barking and Dagenham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000003','Barnet');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000016','Barnsley');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000022','Bath and North East Somerset');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000055','Bedford');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000004','Bexley');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000025','Birmingham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000008','Blackburn with Darwen');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000009','Blackpool');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000019','Blaenau Gwent');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000001','Bolton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000028','Bournemouth');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000036','Bracknell Forest');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000032','Bradford');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000005','Brent');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000013','Bridgend');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000043','Brighton and Hove');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000023','Bristol, City of');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000006','Bromley');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000002','Buckinghamshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000002','Bury');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000018','Caerphilly');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000033','Calderdale');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000003','Cambridgeshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000007','Camden');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000015','Cardiff');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000010','Carmarthenshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000056','Central Bedfordshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000008','Ceredigion');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000049','Cheshire East');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000050','Cheshire West and Chester');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000001','City of London');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000005','Clackmannanshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000003','Conwy');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000052','Cornwall');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000047','County Durham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000026','Coventry');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000008','Croydon');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000006','Cumbria');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000005','Darlington');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000004','Denbighshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000015','Derby');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000007','Derbyshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000008','Devon');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000017','Doncaster');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000009','Dorset');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000027','Dudley');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000006','Dumfries & Galloway');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000042','Dundee City');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000009','Ealing');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000008','East Ayrshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000009','East Dunbartonshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000010','East Lothian');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000011','East Renfrewshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000011','East Riding of Yorkshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000011','East Sussex');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000036','Edinburgh, City of');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000010','Enfield');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000012','Essex');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000014','Falkirk');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000015','Fife');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000005','Flintshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000020','Gateshead');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000043','Glasgow City');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000013','Gloucestershire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000011','Greenwich');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000002','Gwynedd');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000012','Hackney');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000006','Halton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000013','Hammersmith and Fulham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000014','Hampshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000014','Haringey');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000015','Harrow');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000001','Hartlepool');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000016','Havering');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000019','Herefordshire, County of ');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000015','Hertfordshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000017','Highland');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000017','Hillingdon');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000018','Hounslow');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000018','Inverclyde');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000001','Isle of Anglesey');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000046','Isle of Wight');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000053','Isles of Scilly');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000019','Islington');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000020','Kensington and Chelsea');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000016','Kent');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000010','Kingston upon Hull, City of');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000021','Kingston upon Thames');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000034','Kirklees');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000011','Knowsley');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000022','Lambeth');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000017','Lancashire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000035','Leeds');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000016','Leicester');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000018','Leicestershire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000023','Lewisham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000019','Lincolnshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000012','Liverpool');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('EHEATHROW','London Airport (Heathrow)');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000032','Luton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000003','Manchester');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000035','Medway');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000024','Merthyr Tydfil');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000024','Merton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000002','Middlesbrough');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000019','Midlothian');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000042','Milton Keynes');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000021','Monmouthshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000020','Moray');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000013','Na h-Eileanan an Iar (Western Isles)');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000012','Neath Port Talbot');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000021','Newcastle upon Tyne');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000025','Newham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000022','Newport');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000020','Norfolk');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000021','North Ayrshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000012','North East Lincolnshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000044','North Lanarkshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000013','North Lincolnshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000024','North Somerset');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000022','North Tyneside');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000023','North Yorkshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000021','Northamptonshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000048','Northumberland');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000018','Nottingham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000024','Nottinghamshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000004','Oldham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000023','Orkney Islands');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000025','Oxfordshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000009','Pembrokeshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000024','Perth and Kinross');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000031','Peterborough');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000026','Plymouth');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000029','Poole');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000044','Portsmouth');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000023','Powys');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000038','Reading');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000026','Redbridge');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000003','Redcar and Cleveland');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000038','Renfrewshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000016','Rhondda, Cynon, Taff');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000027','Richmond upon Thames');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000005','Rochdale');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000018','Rotherham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000017','Rutland');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000006','Salford');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000028','Sandwell');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000026','Scottish Borders');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000014','Sefton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000019','Sheffield');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000027','Shetland Islands');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000051','Shropshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000039','Slough');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000029','Solihull');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000027','Somerset');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000028','South Ayrshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000025','South Gloucestershire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000029','South Lanarkshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000023','South Tyneside');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000045','Southampton ');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000033','Southend-on-Sea');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000028','Southwark');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000013','St. Helens');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000028','Staffordshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000030','Stirling');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000007','Stockport');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000004','Stockton-on-Tees');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000021','Stoke-on-Trent');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000029','Suffolk');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000024','Sunderland');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000030','Surrey');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000029','Sutton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000011','Swansea');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000030','Swindon');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000008','Tameside');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000020','Telford and Wrekin');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000014','The Vale of Glamorgan');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000034','Thurrock');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000027','Torbay');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000020','Torfaen');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000030','Tower Hamlets');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000009','Trafford');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000036','Wakefield');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000030','Walsall');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000031','Waltham Forest');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000032','Wandsworth');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000007','Warrington');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000031','Warwickshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000037','West Berkshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000039','West Dunbartonshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('S12000040','West Lothian');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000032','West Sussex');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E09000033','Westminster');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000010','Wigan');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000054','Wiltshire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000040','Windsor and Maidenhead');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000015','Wirral');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000041','Wokingham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E08000031','Wolverhampton');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E10000034','Worcestershire');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY,LOCAL_AUTHORITY_HIGHWAY) VALUES ('W06000006','Wrexham');
INSERT INTO LOCAL_AUTHORITY_HIGHWAY (LOCAL_AUTHORITY_HIGHWAY_KEY, LOCAL_AUTHORITY_HIGHWAY) VALUES ('E06000014','York');


ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_LAH
FOREIGN KEY(LOCAL_AUTHORITY_HIGHWAY) 
REFERENCES dbo.LOCAL_AUTHORITY_HIGHWAY(LAH_ID)


--LOCAL_DISTRICT
CREATE TABLE LOCAL_AUTHORITY_DISTRICT
(
	LOCAL_AUTHORITY_DISTRICT_ID INT IDENTITY(1,1) NOT NULL,
	LOCAL_AUTHORITY_DISTRICT_KEY INT,
	LOCAL_AUTHORITY_DISTRICT CHAR(50),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_LOCAL_DISTRICT
    PRIMARY KEY (LOCAL_AUTHORITY_DISTRICT_ID)
)
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('1','Westminster');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('2','Camden');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('3','Islington');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('4','Hackney');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('5','Tower Hamlets');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('6','Greenwich');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('7','Lewisham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('8','Southwark');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('9','Lambeth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('10','Wandsworth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('11','Hammersmith and Fulham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('12','Kensington and Chelsea');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('13','Waltham Forest');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('14','Redbridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('15','Havering');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('16','Barking and Dagenham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('17','Newham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('18','Bexley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('19','Bromley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('20','Croydon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('21','Sutton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('22','Merton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('23','Kingston upon Thames');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('24','Richmond upon Thames');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('25','Hounslow');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('26','Hillingdon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('27','Ealing');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('28','Brent');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('29','Harrow');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('30','Barnet');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('31','Haringey');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('32','Enfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('33','Hertsmere');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('38','Epsom and Ewell');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('40','Spelthorne');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('57','London Airport (Heathrow)');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('60','Allerdale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('61','Barrow-in-Furness');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('62','Carlisle');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('63','Copeland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('64','Eden');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('65','South Lakeland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('70','Blackburn with Darwen');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('71','Blackpool');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('72','Burnley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('73','Chorley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('74','Fylde');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('75','Hyndburn');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('76','Lancaster');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('77','Pendle');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('79','Preston');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('80','Ribble Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('82','Rossendale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('83','South Ribble');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('84','West Lancashire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('85','Wyre');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('90','Knowsley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('91','Liverpool');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('92','St. Helens');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('93','Sefton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('95','Wirral');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('100','Bolton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('101','Bury');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('102','Manchester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('104','Oldham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('106','Rochdale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('107','Salford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('109','Stockport');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('110','Tameside');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('112','Trafford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('114','Wigan');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('120','Chester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('121','Congleton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('122','Crewe and Nantwich');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('123','Ellesmere Port and Neston');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('124','Halton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('126','Macclesfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('127','Vale Royal');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('128','Warrington');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('129','Cheshire East');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('130','Cheshire West and Chester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('139','Northumberland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('140','Alnwick');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('141','Berwick-upon-Tweed');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('142','Blyth Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('143','Castle Morpeth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('144','Tynedale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('145','Wansbeck');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('146','Gateshead');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('147','Newcastle upon Tyne');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('148','North Tyneside');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('149','South Tyneside');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('150','Sunderland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('160','Chester-le-Street');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('161','Darlington');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('162','Derwentside');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('163','Durham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('164','Easington');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('165','Sedgefield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('166','Teesdale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('168','Wear Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('169','County Durham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('180','Craven');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('181','Hambleton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('182','Harrogate');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('184','Richmondshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('185','Ryedale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('186','Scarborough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('187','Selby');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('189','York');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('200','Bradford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('202','Calderdale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('203','Kirklees');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('204','Leeds');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('206','Wakefield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('210','Barnsley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('211','Doncaster');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('213','Rotherham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('215','Sheffield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('228','Kingston upon Hull, City of');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('231','East Riding of Yorkshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('232','North Lincolnshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('233','North East Lincolnshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('240','Hartlepool');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('241','Redcar and Cleveland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('243','Middlesbrough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('245','Stockton-on-Tees');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('250','Cannock Chase');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('251','East Staffordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('252','Lichfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('253','Newcastle-under-Lyme');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('254','South Staffordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('255','Stafford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('256','Staffordshire Moorlands');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('257','Stoke-on-Trent');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('258','Tamworth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('270','Bromsgrove');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('273','Malvern Hills');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('274','Redditch');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('276','Worcester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('277','Wychavon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('278','Wyre Forest');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('279','Bridgnorth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('280','North Shropshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('281','Oswestry');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('282','Shrewsbury and Atcham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('283','South Shropshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('284','Telford and Wrekin');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('285','Herefordshire, County of ');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('286','Shropshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('290','North Warwickshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('291','Nuneaton and Bedworth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('292','Rugby ');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('293','Stratford-upon-Avon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('294','Warwick');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('300','Birmingham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('302','Coventry');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('303','Dudley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('305','Sandwell');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('306','Solihull');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('307','Walsall');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('309','Wolverhampton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('320','Amber Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('321','Bolsover');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('322','Chesterfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('323','Derby');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('324','Erewash');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('325','High Peak');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('327','North East Derbyshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('328','South Derbyshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('329','Derbyshire Dales');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('340','Ashfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('341','Bassetlaw');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('342','Broxtowe');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('343','Gedling');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('344','Mansfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('345','Newark and Sherwood');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('346','Nottingham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('347','Rushcliffe');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('350','Boston');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('351','East Lindsey');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('352','Lincoln');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('353','North Kesteven');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('354','South Holland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('355','South Kesteven');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('356','West Lindsey');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('360','Blaby');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('361','Hinckley and Bosworth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('362','Charnwood');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('363','Harborough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('364','Leicester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('365','Melton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('366','North West Leicestershire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('367','Oadby and Wigston');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('368','Rutland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('380','Corby');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('381','Daventry');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('382','East Northamptonshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('383','Kettering');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('384','Northampton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('385','South Northamptonshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('386','Wellingborough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('390','Cambridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('391','East Cambridgeshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('392','Fenland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('393','Huntingdonshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('394','Peterborough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('395','South Cambridgeshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('400','Breckland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('401','Broadland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('402','Great Yarmouth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('404','Norwich');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('405','North Norfolk');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('406','South Norfolk');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('407','Kings Lynn and West Norfolk');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('410','Babergh');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('411','Forest Heath');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('412','Ipswich');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('413','Mid Suffolk');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('414','St. Edmundsbury');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('415','Suffolk Coastal');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('416','Waveney');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('420','Bedford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('421','Luton');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('422','Mid Bedfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('423','South Bedfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('424','Central Bedfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('430','Broxbourne');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('431','Dacorum');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('432','East Hertfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('433','North Hertfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('434','St. Albans');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('435','Stevenage');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('436','Three Rivers');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('437','Watford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('438','Welwyn Hatfield');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('450','Basildon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('451','Braintree');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('452','Brentwood');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('453','Castle Point');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('454','Chelmsford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('455','Colchester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('456','Epping Forest');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('457','Harlow');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('458','Maldon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('459','Rochford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('460','Southend-on-Sea');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('461','Tendring');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('462','Thurrock');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('463','Uttlesford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('470','Bracknell Forest');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('471','West Berkshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('472','Reading');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('473','Slough');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('474','Windsor and Maidenhead');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('475','Wokingham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('476','Aylesbury Vale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('477','South Bucks');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('478','Chiltern');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('479','Milton Keynes');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('480','Wycombe');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('481','Cherwell');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('482','Oxford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('483','Vale of White Horse');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('484','South Oxfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('485','West Oxfordshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('490','Basingstoke and Deane');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('491','Eastleigh');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('492','Fareham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('493','Gosport');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('494','Hart');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('495','Havant');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('496','New Forest');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('497','East Hampshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('498','Portsmouth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('499','Rushmoor');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('500','Southampton ');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('501','Test Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('502','Winchester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('505','Isle of Wight');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('510','Elmbridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('511','Guildford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('512','Mole Valley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('513','Reigate and Banstead');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('514','Runnymede');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('515','Surrey Heath');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('516','Tandridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('517','Waverley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('518','Woking');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('530','Ashford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('531','Canterbury');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('532','Dartford');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('533','Dover');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('535','Gravesham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('536','Maidstone');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('538','Sevenoaks');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('539','Shepway');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('540','Swale');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('541','Thanet');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('542','Tonbridge and Malling');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('543','Tunbridge Wells');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('544','Medway');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('551','Eastbourne');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('552','Hastings');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('554','Lewes');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('555','Rother');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('556','Wealden');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('557','Adur');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('558','Arun');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('559','Chichester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('560','Crawley');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('562','Horsham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('563','Mid Sussex');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('564','Worthing');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('565','Brighton and Hove');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('570','City of London');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('580','East Devon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('581','Exeter');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('582','North Devon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('583','Plymouth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('584','South Hams');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('585','Teignbridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('586','Mid Devon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('587','Torbay');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('588','Torridge');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('589','West Devon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('590','Caradon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('591','Carrick');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('592','Kerrier');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('593','North Cornwall');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('594','Penwith');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('595','Restormel');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('596','Cornwall');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('601','Bristol, City of');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('605','North Somerset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('606','Mendip');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('607','Sedgemoor');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('608','Taunton Deane');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('609','West Somerset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('610','South Somerset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('611','Bath and North East Somerset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('612','South Gloucestershire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('620','Cheltenham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('621','Cotswold');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('622','Forest of Dean');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('623','Gloucester');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('624','Stroud');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('625','Tewkesbury');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('630','Kennet');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('631','North Wiltshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('632','Salisbury');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('633','Swindon');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('634','West Wiltshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('635','Wiltshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('640','Bournemouth');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('641','Christchurch');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('642','North Dorset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('643','Poole');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('644','Purbeck');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('645','West Dorset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('646','Weymouth and Portland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('647','East Dorset');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('720','Isle of Anglesey');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('721','Conwy');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('722','Gwynedd');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('723','Denbighshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('724','Flintshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('725','Wrexham');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('730','Blaenau Gwent');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('731','Caerphilly');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('732','Monmouthshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('733','Newport');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('734','Torfaen');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('740','Bridgend');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('741','Cardiff');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('742','Merthyr Tydfil');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('743','Neath Port Talbot');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('744','Rhondda, Cynon, Taff');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('745','Swansea');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('746','The Vale of Glamorgan');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('750','Ceredigion');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('751','Carmarthenshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('752','Pembrokeshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('753','Powys');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('910','Aberdeen City');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('911','Aberdeenshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('912','Angus');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('913','Argyll and Bute');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('914','Scottish Borders');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('915','Clackmannanshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('916','West Dunbartonshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('917','Dumfries and Galloway');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('918','Dundee City');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('919','East Ayrshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('920','East Dunbartonshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('921','East Lothian');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('922','East Renfrewshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('923','Edinburgh, City of');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('924','Falkirk');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('925','Fife');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('926','Glasgow City');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('927','Highland');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('928','Inverclyde');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('929','Midlothian');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('930','Moray');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('931','North Ayrshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('932','North Lanarkshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('933','Orkney Islands');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('934','Perth and Kinross');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('935','Renfrewshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('936','Shetland Islands');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('937','South Ayrshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('938','South Lanarkshire');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('939','Stirling');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('940','West Lothian');
INSERT INTO LOCAL_AUTHORITY_DISTRICT (LOCAL_AUTHORITY_DISTRICT_KEY, LOCAL_AUTHORITY_DISTRICT) VALUES ('941','Western Isles');

ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_LAD
FOREIGN KEY(LOCAL_AUTHORITY_DISTRICT_ID) 
REFERENCES dbo.LOCAL_AUTHORITY_DISTRICT(LOCAL_AUTHORITY_DISTRICT_ID)


CREATE TABLE TIME_PERIOD
(
    TIME_PERIOD_ID INT IDENTITY(1,1) NOT NULL,
	TIME_PERIOD_KEY INT,
	PERIOD_NAME CHAR(25),
	PERIOD_VALUE CHAR(25),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_DIM_TIME_PERIOD
    PRIMARY KEY (TIME_PERIOD_ID)
)

INSERT INTO TIME_PERIOD VALUES ('1','MORNING','5AM-12PM',NULL,NULL)
INSERT INTO TIME_PERIOD VALUES ('2','AFTERNOON','12PM-5PM',NULL,NULL)
INSERT INTO TIME_PERIOD VALUES ('3','EVENING','5PM-9PM',NULL,NULL)
INSERT INTO TIME_PERIOD VALUES ('4','NIGHT','9PM-5AM',NULL,NULL)
INSERT INTO TIME_PERIOD VALUES ('5','ERROR OR MISSING VALUES','ERROR OR MISSING VALUES',NULL,NULL)


ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_TIME_PERIOD
FOREIGN KEY(TIME_PERIOD_ID) 
REFERENCES dbo.TIME_PERIOD(TIME_PERIOD_ID)



CREATE TABLE BUILD_UP_ROAD
(
	BUILD_UP_ROAD_ID INT IDENTITY(1,1) NOT NULL,
	BUILD_UP_ROAD CHAR(30),
	CREATED_DATE DATETIME,
	UPDATE_DATE DATETIME

	CONSTRAINT PK_BUILD_UP_ROAD
    PRIMARY KEY (BUILD_UP_ROAD_ID)
)

ALTER TABLE dbo.ACCIDENTS
ADD CONSTRAINT FK_ACCIDENTS_BUR
FOREIGN KEY (BUILD_UP_ROAD) 
REFERENCES dbo.BUILD_UP_ROAD(BUILD_UP_ROAD_ID)

INSERT INTO BUILD_UP_ROAD VALUES ('Built-up road',null,null)
INSERT INTO BUILD_UP_ROAD VALUES ('Non Built-up road',NULL,NULL)