use  master 
go
if DB_ID ('META_UK') IS NOT NULL
    DROP DATABASE META_UK
GO
CREATE DATABASE META_UK
GO
USE META_UK
GO

CREATE TABLE TABLE_INFO
(
	ID INT,
	TABLE_NAME CHAR(50),
	LSET DATETIME,
	CET DATETIME,
	DESCRIBE VARCHAR(50),
	NUMBER_OF_RECORD INT

	CONSTRAINT PK_TABLE_INFO
    PRIMARY KEY (ID)
)

INSERT INTO TABLE_INFO VALUES ('1','ACCIDENTS','2021-10-26',NULL,NULL,(SELECT COUNT(*) FROM STAGE.dbo.ACCIDENTS))
INSERT INTO TABLE_INFO VALUES ('2','CASUALTIES','2021-10-26',NULL,NULL,(SELECT COUNT(*) FROM STAGE.dbo.CASUALTIES))
INSERT INTO TABLE_INFO VALUES ('3','VEHICLES','2021-10-26',NULL,NULL,(SELECT COUNT(*) FROM STAGE.dbO.VEHICLES))
INSERT INTO TABLE_INFO VALUES ('4','POSTCODE','2021-10-26',NULL,NULL,(SELECT COUNT(*) FROM STAGE.dbo.POSTCODE))
INSERT INTO TABLE_INFO VALUES ('5','LSOA_INFO','2021-10-26',NULL,NULL,(SELECT COUNT(*) FROM STAGE.dbo.LSOA_INFO))


CREATE TABLE COLUMN_TYPE
(
	ID INT,
	TYPES_NAME VARCHAR(30),
	DESCRIBE VARCHAR(50)
	

	CONSTRAINT PK_COLUMN_TYPE
    PRIMARY KEY (ID)
)

CREATE TABLE DATA_DEFINITION
(
	ID INT,
	TABLE_ID INT,
	COLUMN_NAME VARCHAR(30),
	COLUMN_TYPE INT,
	DESCRIBE VARCHAR(50),
	SAMPLE_VALUE VARCHAR(30)

	CONSTRAINT PK_DATA_DEFINITION
    PRIMARY KEY (ID)
)

ALTER TABLE DATA_DEFINITION
ADD CONSTRAINT FK_DATA_TABLE
FOREIGN KEY (TABLE_ID)
REFERENCES TABLE_INFO(ID)

ALTER TABLE DATA_DEFINITION
ADD CONSTRAINT FK_DATA_COLUMN
FOREIGN KEY (COLUMN_TYPE)
REFERENCES COLUMN_TYPE(ID)


CREATE TABLE PACKAGE_DEFINITION
(
	ID INT,
	PACKAGE_NAME VARCHAR(30),
	DESCRIBE VARCHAR(50),
	SCHEDULE VARCHAR(30)

	CONSTRAINT PK_PACKAGE_DEFINITION
    PRIMARY KEY (ID)
)