THIS IS THE SSIS PACKAGE USE IN ETL PROCESS: 
THIS INCLUDE 
- DATA PROFILING
- ETL DATA FROM SOURCE TO STAGE DATABASE (TRUNCATE METHOD)
- ETL DATA FROM STAGE DATABASE TO NDS DATABASE (INCREMENT METHOD)
- ETL DATA FROM NDS DATABASE TO DDS DATABASE (SORE OF INCREMENT METHOD)
